config/routes.rb
Crowdfunder::Application.routes.draw do
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :projects
  resources :users
  resources :sessions
  root to: "projects#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_authenticated
  	redirect_to login_url, :alert => "First login to access this page."
end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :require_login, :only => [:create, :new]


  def index
  	@projects = Project.all
  end

  def show
  	@project = Project.find(params[:id])
  end

  def new
  	@project = Project.new
  end

  def edit
  	@project = Project.find(params[:id])
  end

  def create
  	@project = Project.new(project_params)

  	if @project.save
  		redirect_to projects_url
  	else
  		render :new
  	end
  end

  def update
  	@project = Project.find(params[:id])

  	if @project.update_attributes(project_params)
  		redirect_to project_path(@project)
  	else
  		render :edit
  	end
  end

  private
  def project_params
  	params.require(:project).permit(:title, :description, :goal, :start_date, :end_date, :picture_url)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create

		if @user = login(params[:email], params[:password])
			redirect_back_or_to root_url, :notice => "Logged in!"
		else
			flash.now.alert = "Email or password was invalid"
			render :new
		end
	end


	def destroy
		logout
		redirect_back_or_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_url, :notice => "Signed up!"
		else
			render :new
		end
	end



private

def user_params
	params.require(:user).permit(:email, :password, :password_confirmation)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "CrowdFunder", root_url, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <% if current_user %>
            <font color=white>Logged in as <%= current_user.email %></font>
              <%= link_to "Log out", session_path("current"), :method => :delete %>
                <% else %>
              <%= link_to "Sign up", new_user_path %> or
              <%= link_to "Log in", new_session_path %>
            <% end %>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfunder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div id="flash">
	<% if flash[:notice] %>
		<p id="notice"><%= flash[:notice] %></p>
<% end %>

	<% if flash[:alert] %>
		<p id="alert"><%= flash[:alert] %></p>
<% end %>

</div>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :goal %><br />
    <%= f.number_field :goal %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.datetime_select :end_date %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture_url %><br />
    <%= f.text_field :picture_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<img src="<%= project[:picture_url] %>" />

<h2><strong>$<%= project.goal %><br /></strong></h2>
<span><strong>Start Date: </strong><%= project.start_date %></span><br />
<span><strong>End Date: </strong><%= project.end_date %></span><br />
<span><strong>Description: </strong><%= project.description[0..50] %><%= link_to "[...read more]", project%></span><br />

app/views/projects/edit.html.erb
<h1>Edit Project Details</h1>

<p>
	<%= link_to "Back", @project %>
</p>

<%= form_for @project do |f| %>
	<p>
		<%= f.label "title" %><br>
		<%= f.text_field "title" %>
	</p>
	<p>
		<%= f.label "description" %><br>
		<%= f.text_field "description" %>
	</p>
	<p>
		<%= f.label "goal" %><br>
		<%= f.text_field "goal" %>
	</p>
	<p>
		<%= f.label "start_date" %><br>
		<%= f.text_field "start_date" %>
	</p>
	<p>
		<%= f.label "end_date" %><br>
		<%= f.text_field "end_date" %>
	</p>
	<p>
		<%= f.label "picture_url" %><br>
		<%= f.text_field "picture_url" %>
	</p>
	<p>
		<%= submit_tag "Save"  %>
	</p>

	<% end %>

app/views/projects/index.html.erb
<h1>All Projects</h1>

<% @projects.each do |project| %>
	<%= link_to project do %>
	<h2><%= project.title %></h2>
	<% end %>
	<%= render project %>
<% end  %>

app/views/projects/new.html.erb
<h1>New Projects</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<%= @project[:title] %>
<%= render @project %>
<br>
<br>
<%= link_to "Edit Project", edit_project_path(@project) %> | <%= link_to 'Back', root_url %>

app/views/users/index.html.erb
<h1> Hello </h1>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
			<h2>Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
					<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

<div class ="field">
	<%= f.label :email %>
	<%= f.text_field :email %>
</div>

<div class="field">
	<%= f.label :password %>
	<%= f.password_field :password %>
</div>

<div class="field">
	<%= f.label :password_confirmation %>
	<%= f.password_field :password_confirmation %>
</div>

<div class="actions"><%= f.submit %></div>

<% end %>